apiVersion: v1
kind: Namespace
metadata:
  name: network-hedgehog-defence
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: network-hedgehog-defence
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: "external"
      nodePort: 32222
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: network-hedgehog-defence
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: "database"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: setup
  namespace: default
spec:
  selector:
    matchLabels:
      app: setup
  replicas: 2
  template:
    metadata:
      labels:
        app: setup
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: network-hedgehog-defence
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        ports:
        - containerPort: 80
          name: external
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: network-hedgehog-defence
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
          name: database
        volumeMounts:
        - name: db
          mountPath: "/docker-entrypoint-initdb.d"
          readOnly: true
      volumes:
      - name: db
        secret:
          secretName: database
---
apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: network-hedgehog-defence
type: Opaque
data:
  secrets.sql: Q1JFQVRFIFRBQkxFIHNlY3JldHMgKHNlY3JldCAgICAgQ0hBUig1MCkgICAgICAgTk9UIE5VTEwpOwpJTlNFUlQgSU5UTyBzZWNyZXRzIFZBTFVFUyAoJ292ZXI5MDAwY3JlZGl0Y2FyZG51bWJlcnMnKTsK
