apiVersion: v1
kind: Namespace
metadata:
  name: rbac-flanking-maneuver

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-flanking-maneuver
  namespace: rbac-flanking-maneuver

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-flanking-maneuver
  namespace: rbac-flanking-maneuver
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: rbac-flanking-maneuver
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: admin

---

kind: Service
apiVersion: v1
metadata:
  name: jumpbox
  namespace: rbac-flanking-maneuver
spec:
  selector:
    name: jumpbox
  type: NodePort
  ports:
  - port: 22
    nodePort: 30022
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: jumpbox
  name: jumpbox
  namespace: rbac-flanking-maneuver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jumpbox
  template:
    metadata:
      labels:
        name: jumpbox
    spec:
      serviceAccountName: rbac-flanking-maneuver
      containers:
      - image: controlplane/insecure-ssh
        imagePullPolicy: IfNotPresent
        name: jumpbox
        ports:
        - containerPort: 22
