---
apiVersion: v1
kind: Namespace
metadata:
  name: rbac-shoot-and-scoot
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-shoot-and-scoot
subjects:
- kind: User
  name: system:anonymous
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: admin

---

apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: rbac-shoot-and-scoot
type: Opaque
data:
  credentials: b2hub2NyZWRlbnRpYWxzYXJlaGVyZQo=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rbac-shoot-and-scoot
  name: ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      automountServiceAccountToken: false
      containers:
      - name: ubuntu
        image: ubuntu:18.04
        args: [bash, -c, 'sleep infinity']
