apiVersion: v1
kind: Namespace
metadata:
  name: policy-vertical-envelopment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: policy-vertical-envelopment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: policy-vertical-envelopment
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
      - name: jenkins
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        securityContext:
          privileged: true
