apiVersion: v1
kind: Namespace
metadata:
  name: container-ambush

---

apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: container-ambush
type: Opaque
data:
  password: c3VwZXJTZWNyZXRQYXNzd29yZAo=

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: jenkins
  name: jenkins
  namespace: container-ambush
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      containers:
      - image: nginx
        # image: vulnerables/cve-2014-6271
        imagePullPolicy: IfNotPresent
        name: jenkins
        ports:
        - containerPort: 80
        volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
          readOnly: true
      - image: ubuntu:16.04
        imagePullPolicy: IfNotPresent
        name: db
        volumeMounts:
        - name: db
          readOnly: true
          mountPath: "/etc/secret-volume"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: db
        secret:
          secretName: db
