apiVersion: v1
kind: Namespace
metadata:
  name: network-swarming
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: network-swarming
spec:
  selector:
    matchLabels:
      app: frontend
      project: webapidb
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
        project: webapidb
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        ports:
        - containerPort: 80
          name: external
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: network-swarming
spec:
  selector:
    matchLabels:
      app: api
      project: webapidb
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        project: webapidb
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: network-swarming
spec:
  selector:
    matchLabels:
      app: db
      project: webapidb
  replicas: 1
  template:
    metadata:
      labels:
        app: db
        project: webapidb
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
          name: database
        volumeMounts:
        - name: db
          mountPath: "/docker-entrypoint-initdb.d"
          readOnly: true
      volumes:
      - name: db
        secret:
          secretName: database
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: network-swarming
spec:
  type: NodePort
  selector:
    project: webapidb
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: "external"
      nodePort: 32222
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: network-swarming
spec:
  type: ClusterIP
  selector:
    project: webapidb
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: "api"
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: network-swarming
spec:
  type: ClusterIP
  selector:
    project: webapidb
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: "database"
---
apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: network-swarming
type: Opaque
data:
  secrets.sql: Q1JFQVRFIFRBQkxFIHNlY3JldHMgKHNlY3JldCAgICAgQ0hBUig1MCkgICAgICAgTk9UIE5VTEwpOwpJTlNFUlQgSU5UTyBzZWNyZXRzIFZBTFVFUyAoJzEwMDBjcmVkaXRjYXJkbnVtYmVycycpOwo=
