apiVersion: v1
kind: Namespace
metadata:
  name: network-feint

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: network-feint
spec:
  selector:
    matchLabels:
      app: nginx
      project: webdb
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        project: webdb
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: external
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: network-feint
spec:
  selector:
    matchLabels:
      app: postgres
      project: webdb
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        project: webdb
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
          name: external
        volumeMounts:
        - name: db
          mountPath: "/docker-entrypoint-initdb.d"
          readOnly: true
      volumes:
      - name: db
        secret:
          secretName: database
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: network-feint
spec:
  type: NodePort
  selector:
    project: webdb
  ports:
    - protocol: TCP
      port: 80
      targetPort: "external"
      nodePort: 32123
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: network-feint
spec:
  type: ClusterIP
  selector:
    project: webdb
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: "external"
---
apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: network-feint
type: Opaque
data:
  secrets.sql: Q1JFQVRFIFRBQkxFIHNlY3JldHMgKHNlY3JldCAgICAgQ0hBUig1MCkgICAgICAgTk9UIE5VTEwpOwpJTlNFUlQgSU5UTyBzZWNyZXRzIFZBTFVFUyAoJ3NlY3JldGhlcmJzYW5kc3BpY2VzJyk7Cg==
