apiVersion: v1
kind: Namespace
metadata:
  name: etcd-inverted-wedge
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: etcd-inverted-wedge
type: Opaque
data:
  credentials: b2hub2NyZWRlbnRpYWxzYXJlaGVyZQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: etcd-inverted-wedge
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:18.04
        args: [bash, -c, 'sleep infinity']
