apiVersion: v1
kind: Namespace
metadata:
  name: node-amphibious-operations
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: node-amphibious-operations
  labels:
    name: malicious-pod
  name: malicious-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: malicious-pod
  template:
    metadata:
      labels:
        name: malicious-pod
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        ports:
        - containerPort: 80
          name: external
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: node-amphibious-operations
spec:
  selector:
    matchLabels:
      app: frontend
      project: webapidb
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
        project: webapidb
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        ports:
        - containerPort: 80
          name: external
