apiVersion: v1
kind: Namespace
metadata:
  name: node-amphibious-operations
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: node-amphibious-operations
  labels:
    name: super-secret-pod
  name: super-secret-pod
spec:
  selector:
    matchLabels:
      name: super-secret-pod
  replicas: 1
  template:
    metadata:
      labels:
        name: super-secret-pod
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        ports:
        - containerPort: 80
          name: external
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: start-pod
  namespace: node-amphibious-operations
spec:
  selector:
    matchLabels:
      name: start-pod
  replicas: 1
  template:
    metadata:
      labels:
        name: start-pod
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        ports:
        - containerPort: 80
          name: external
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: node-amphibious-operations
type: Opaque
data:
  username: dXNlcmlzdXNlcgo=
  password: cGFzc3dvcmRpc3Bhc3N3b3JkCg==
