apiVersion: v1
kind: Namespace
metadata:
  name: network-hammer-and-anvil
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: network-hammer-and-anvil
spec:
  selector:
    matchLabels:
      app: frontend
      project: webapidb
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
        project: webapidb
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        ports:
        - containerPort: 80
          name: external
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: network-hammer-and-anvil
spec:
  selector:
    matchLabels:
      app: db
      project: webapidb
  replicas: 1
  template:
    metadata:
      labels:
        app: db
        project: webapidb
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
          name: database
        volumeMounts:
        - name: db
          mountPath: "/docker-entrypoint-initdb.d"
          readOnly: true
        - name: file
          mountPath: "/backups"
      initContainers:
      - name: file
        image: ubuntu
        command:
        - dd
        - "if=/dev/zero"
        - "of=/work-dir/database.txt"
        - "count=512"
        - "bs=1048576"
        volumeMounts:
        - name: file
          mountPath: "/work-dir"
      volumes:
      - name: db
        secret:
          secretName: database
      - name: file
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: network-hammer-and-anvil
spec:
  type: ClusterIP
  selector:
    project: webapidb
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: "database"
---
apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: network-hammer-and-anvil
type: Opaque
data:
  secrets.sql: Q1JFQVRFIFRBQkxFIHNlY3JldHMgKHNlY3JldCAgICAgQ0hBUig1MCkgICAgICAgTk9UIE5VTEwpOwpJTlNFUlQgSU5UTyBzZWNyZXRzIFZBTFVFUyAoJ25vdHRoZXNlY3JldHN5b3VhcmVsb29raW5nZm9yJyk7Cg==
