apiVersion: v1
kind: Namespace
metadata:
  name: node-raiding
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: node-raiding
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        env:
        - name: SECRET_PASSWORD
          value: aW5jcmVkaWJseVNlY3JldEluZm9ybWF0aW9uCg==
